#![allow(non_upper_case_globals)]
#![cfg_attr(not(feature = "host"), allow(unused))]

pub(crate) struct C;

macro_rules! class {
    ($($name:ident,)*) => {
        impl C {
            $(
                pub(crate) const $name: &str = stringify!($name);
            )*
        }
    };
}

class! {
    arg_colon,
    arg_comma,
    arg_em_dash,
    arg_equals,
    arg_link,
    arg_name,
    arg_ty,
    arg_ty_nullable,
    badge_destructor,
    badge_normal,
    badges,
    compositor_support,
    compositor_support_title,
    compositor_support_version,
    compositor_support_version_list,
    compositor_support_version_list_element,
    compositor_version,
    copyright,
    deprecated_hue,
    description,
    drop_zone,
    drop_zone_hint,
    drop_zone_title,
    enum_hue,
    enum_paren,
    error,
    error_detail,
    event_hue,
    event_paren,
    field_hint,
    field_label,
    field_row,
    file_input,
    frozen_hue,
    generic_link,
    index_desc,
    index_intro,
    index_outro,
    index_toc,
    info,
    interface_header,
    interface_hue,
    interface_name,
    interface_protocol_link,
    keyword,
    lowkey,
    main_arg_name,
    main_link,
    member_name,
    message_body,
    message_interface_link,
    message_signature,
    noselect,
    open_link,
    output,
    output_bar,
    output_links,
    output_title,
    output_wrap,
    panel,
    paste_input,
    paste_render,
    protocol_header,
    protocol_index,
    protocol_prefix,
    protocol_toc,
    protocol_url,
    render_btn,
    render_intro,
    request_hue,
    request_paren,
    retry_link,
    share_link,
    status,
    suite_name,
    summary,
    tab,
    tabs,
    toc,
    toc_summary,
    top,
    type_hue,
    type_modifier_hue,
    url_input,
    url_render,
}
